swagger: "2.0"
info:
  version: "0.0.1"
  title: Contacts App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/form-data
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/html
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /contacts:
    # binds a127 app logic to a route
    x-swagger-router-controller: contacts
    get:
      description: Returns contacts list
      # used as the method name of the controller
      operationId: getAllContacts
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ContactsList"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
    post:
      description: Creates New Contact
      # used as the method name of the controller
      operationId: createContact
      parameters:
        - name: firstname
          in: formData
          description: The firstname of the person
          required: true
          type: string
        - name: lastname
          in: formData
          description: The lastname of the person
          required: true
          type: string
        - name: phonenumber
          in: formData
          description: The phonenumber of the person
          required: true
          type: string  
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ContactNew"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  
  /contacts/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: contacts
    get:
      description: Returns the particular contact
      # used as the method name of the controller
      operationId: getContact
      parameters:
        - name: id
          in: path
          description: Unique ID of the contact
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ContactsList"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Updates the particular contact
      # used as the method name of the controller
      operationId: updateContact
      parameters:
        - name: id
          in: path
          description: Unique ID of the contact
          required: true
          type: string
        - name: firstname
          in: formData
          description: Firstname of the contact
          required: false
          type: string
        - name: lastname
          in: formData
          description: Lastname ID of the contact
          required: false
          type: string
        - name: phonenumber
          in: formData
          description: Phonenumber of the contact
          required: false
          type: string      
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ContactsList"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  ContactsList:
    required:
      - contacts
    properties:
      contacts:
        type: array
        items: 
          $ref: "#/definitions/Contacts"
  ContactNew:
    required:
      - contacts
    properties:
      contacts:
        type: array
        items: 
          $ref: "#/definitions/Contacts"        
  Contacts:
    required:
      - firstname
      - lastname
      - phonenumber
    properties:
      firstname:
        type: string
      lastname:
        type: string
      phonenumber:
        type: string
